#pragma once
#include <lvgl.h>
#include <string.h>

// Custom MDI weather icon fonts (generated by lv_font_conv)
extern lv_font_t weather_font_40;  // 40px - for current weather
extern lv_font_t weather_font_24;  // 24px - for forecast cards

// MDI weather icon codepoints (UTF-8 encoded)
// These map to glyphs in the weather_font_40 and weather_font_24 fonts
#define ICON_WEATHER_CLOUDY          "\xF3\xB0\x96\x90"  // U+F0590
#define ICON_WEATHER_FOG             "\xF3\xB0\x96\x91"  // U+F0591
#define ICON_WEATHER_HAIL            "\xF3\xB0\x96\x92"  // U+F0592
#define ICON_WEATHER_LIGHTNING       "\xF3\xB0\x96\x93"  // U+F0593
#define ICON_WEATHER_NIGHT           "\xF3\xB0\x96\x94"  // U+F0594
#define ICON_WEATHER_PARTLY_CLOUDY   "\xF3\xB0\x96\x95"  // U+F0595
#define ICON_WEATHER_POURING         "\xF3\xB0\x96\x96"  // U+F0596
#define ICON_WEATHER_RAINY           "\xF3\xB0\x96\x97"  // U+F0597
#define ICON_WEATHER_SNOWY           "\xF3\xB0\x96\x98"  // U+F0598
#define ICON_WEATHER_SUNNY           "\xF3\xB0\x96\x99"  // U+F0599
#define ICON_WEATHER_SUNSET_UP       "\xF3\xB0\x96\x9C"  // U+F059C
#define ICON_WEATHER_WINDY           "\xF3\xB0\x96\x9D"  // U+F059D
#define ICON_WEATHER_WINDY_VARIANT   "\xF3\xB0\x96\x9E"  // U+F059E
#define ICON_WEATHER_LIGHTNING_RAINY "\xF3\xB0\x99\xBE"  // U+F067E
#define ICON_WEATHER_SUNNY_ALERT     "\xF3\xB0\xBC\xB7"  // U+F0F37

// Map HA weather condition strings to display label and icon string
struct WeatherDisplay {
    const char* label;
    const char* icon;
};

inline WeatherDisplay weather_get_display(const char* condition) {
    if (!condition) return {"Unknown", ICON_WEATHER_CLOUDY};

    if (strcmp(condition, "sunny") == 0)            return {"Sunny",        ICON_WEATHER_SUNNY};
    if (strcmp(condition, "clear-night") == 0)       return {"Clear",        ICON_WEATHER_NIGHT};
    if (strcmp(condition, "partlycloudy") == 0)      return {"Partly Cloudy",ICON_WEATHER_PARTLY_CLOUDY};
    if (strcmp(condition, "cloudy") == 0)             return {"Cloudy",       ICON_WEATHER_CLOUDY};
    if (strcmp(condition, "fog") == 0)                return {"Foggy",        ICON_WEATHER_FOG};
    if (strcmp(condition, "rainy") == 0)              return {"Rainy",        ICON_WEATHER_RAINY};
    if (strcmp(condition, "pouring") == 0)            return {"Pouring",      ICON_WEATHER_POURING};
    if (strcmp(condition, "snowy") == 0)              return {"Snowy",        ICON_WEATHER_SNOWY};
    if (strcmp(condition, "snowy-rainy") == 0)        return {"Sleet",        ICON_WEATHER_SNOWY};
    if (strcmp(condition, "hail") == 0)               return {"Hail",         ICON_WEATHER_HAIL};
    if (strcmp(condition, "lightning") == 0)           return {"Thunder",      ICON_WEATHER_LIGHTNING};
    if (strcmp(condition, "lightning-rainy") == 0)     return {"Thunderstorm", ICON_WEATHER_LIGHTNING_RAINY};
    if (strcmp(condition, "windy") == 0)              return {"Windy",        ICON_WEATHER_WINDY};
    if (strcmp(condition, "windy-variant") == 0)      return {"Windy",        ICON_WEATHER_WINDY_VARIANT};
    if (strcmp(condition, "exceptional") == 0)         return {"Exceptional",  ICON_WEATHER_SUNNY_ALERT};

    return {"Unknown", ICON_WEATHER_CLOUDY};
}
